// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum ActorStatus : int {
  IDLE = 0,
  MOVING = 1,
  INTERACTING = 2,
  DEAD = 3,
  ATTACKING = 4,
  ActorStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ActorStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ActorStatus_IsValid(int value);
constexpr ActorStatus ActorStatus_MIN = IDLE;
constexpr ActorStatus ActorStatus_MAX = ATTACKING;
constexpr int ActorStatus_ARRAYSIZE = ActorStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ActorStatus_descriptor();
template<typename T>
inline const std::string& ActorStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ActorStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ActorStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ActorStatus_descriptor(), enum_t_value);
}
inline bool ActorStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ActorStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ActorStatus>(
    ActorStatus_descriptor(), name, value);
}
enum ActorRole : int {
  DEFAULT = 0,
  PLAYER = 1,
  AI = 2,
  ENVIRONMENT = 3,
  ActorRole_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ActorRole_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ActorRole_IsValid(int value);
constexpr ActorRole ActorRole_MIN = DEFAULT;
constexpr ActorRole ActorRole_MAX = ENVIRONMENT;
constexpr int ActorRole_ARRAYSIZE = ActorRole_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ActorRole_descriptor();
template<typename T>
inline const std::string& ActorRole_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ActorRole>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ActorRole_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ActorRole_descriptor(), enum_t_value);
}
inline bool ActorRole_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ActorRole* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ActorRole>(
    ActorRole_descriptor(), name, value);
}
enum ErrorCode : int {
  NONE = 0,
  INVALID_CREDENTIALS = 1,
  SERVER_FULL = 2,
  UNKNOWN_ERROR = 99,
  ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ErrorCode_IsValid(int value);
constexpr ErrorCode ErrorCode_MIN = NONE;
constexpr ErrorCode ErrorCode_MAX = UNKNOWN_ERROR;
constexpr int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorCode_descriptor();
template<typename T>
inline const std::string& ErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorCode_descriptor(), enum_t_value);
}
inline bool ErrorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorCode>(
    ErrorCode_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::ActorStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ActorStatus>() {
  return ::Protocol::ActorStatus_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ActorRole> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ActorRole>() {
  return ::Protocol::ActorRole_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ErrorCode>() {
  return ::Protocol::ErrorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
